Name:             apkg-ex-multiple-sources
Version:          {{ version }}
Release:          {{ release }}%{?dist}
Summary:          minimal example of a package with multiple source files

License:          GPL 3.0
Source0:          %{name}-v%{version}+repack.tar.gz
Source1:          extra-v0.5.tar.gz
Source2:          files.tar.gz

BuildArch:        noarch

%description
This is a minimal example of apkg templating features.

%prep
# postpone autopatch until we have all sources
%autosetup -N -n %{name}-v%{version} -S git
# extract components in their directories
%setup -DT -a 1 -c -n %{name}-v%{version}/extra
%setup -DT -a 2 -c -n %{name}-v%{version}/files
# switch back to the main directory
%setup -DT -n %{name}-v%{version}
%autopatch

%files
%doc README.md
%doc extra/README.md
%doc files/README.md

%changelog
* {{ now }} Jakub Ružička <jru@debian.org> - {{ version }}-{{ release }}
- A compat 5 project with multiple sources generated by make_archive
