variables:
  LC_ALL: C.UTF-8


stages:
  - test
  - bird
  - knot-dns
  - knot-resolver
  - deploy


image: $CI_REGISTRY/packaging/apkg/ci/debian-10-full:apkg


.setup-git: &setup-git
  - git config --global user.name CI
  - git config --global user.email ci@nic

.setup-py-reqs: &setup-py-reqs
  - pip3 install -r requirements.txt

.setup-py-develop: &setup-py-develop
  - python3 setup.py develop --user

.setup-project: &setup-project
  - *setup-git
  - *setup-py-develop


.test: &test
  stage: test

.bird: &bird
  stage: bird
  only:
    variables:
      - $INTEGRATION
  needs:
    - unit

.knot-dns: &knot-dns
  stage: knot-dns
  only:
    variables:
      - $INTEGRATION
  needs:
    - unit

.knot-resolver: &knot-resolver
  stage: knot-resolver
  only:
    variables:
      - $INTEGRATION
  needs:
    - unit


# basic tests

flake8:
  <<: *test
  script:
    - tox -e flake8

pylint:
  <<: *test
  allow_failure: true
  script:
    - tox -e pylint

unit:
  <<: *test
  script:
    - tox -e unit

self:
  <<: *test
  script:
    # `python3 -m build` causes issues in tox in docker container
    # use py.test directly
    - *setup-py-reqs
    - *setup-py-develop
    - py.test-3 -v tests/self


# integration tests: BIRD

debian-10-bird:
  image: $CI_REGISTRY/packaging/apkg/ci/debian-10:apkg
  <<: *bird
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_bird.py

ubuntu-18.04-bird:
  image: $CI_REGISTRY/packaging/apkg/ci/ubuntu-18.04:apkg
  <<: *bird
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_bird.py
  # TODO: dpkg: error: PATH is not set
  allow_failure: true

ubuntu-20.04-bird:
  image: $CI_REGISTRY/packaging/apkg/ci/ubuntu-20.04:apkg
  <<: *bird
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_bird.py

fedora-33-bird:
  image: $CI_REGISTRY/packaging/apkg/ci/fedora-33:apkg
  <<: *bird
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_bird.py

suse-15-bird:
  image: $CI_REGISTRY/packaging/apkg/ci/suse-15:apkg
  <<: *bird
  script:
    - *setup-project
    - py.test3 -v ci/tests/test_bird.py


# integration tests: Knot DNS

debian-10-knot-dns:
  image: $CI_REGISTRY/packaging/apkg/ci/debian-10:apkg
  <<: *knot-dns
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_dns.py

ubuntu-18.04-knot-dns:
  image: $CI_REGISTRY/packaging/apkg/ci/ubuntu-18.04:apkg
  <<: *knot-dns
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_dns.py
  # TODO: dpkg: error: PATH is not set
  allow_failure: true

ubuntu-20.04-knot-dns:
  image: $CI_REGISTRY/packaging/apkg/ci/ubuntu-20.04:apkg
  <<: *knot-dns
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_dns.py

fedora-33-knot-dns:
  image: $CI_REGISTRY/packaging/apkg/ci/fedora-33:apkg
  <<: *knot-dns
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_dns.py

suse-15-knot-dns:
  image: $CI_REGISTRY/packaging/apkg/ci/suse-15:apkg
  <<: *knot-dns
  script:
    - *setup-project
    - py.test3 -v ci/tests/test_knot_dns.py


# integration tests: Knot Resolver

debian-10-knot-resolver:
  image: $CI_REGISTRY/packaging/apkg/ci/debian-10:apkg
  <<: *knot-resolver
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_resolver.py
  # TODO: problems with root build
  allow_failure: true

ubuntu-18.04-knot-resolver:
  image: $CI_REGISTRY/packaging/apkg/ci/ubuntu-18.04:apkg
  <<: *knot-resolver
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_resolver.py
  # TODO: dpkg: error: PATH is not set
  allow_failure: true

ubuntu-20.04-knot-resolver:
  image: $CI_REGISTRY/packaging/apkg/ci/ubuntu-20.04:apkg
  <<: *knot-resolver
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_resolver.py
  # TODO: problems with root build
  allow_failure: true

fedora-33-knot-resolver:
  image: $CI_REGISTRY/packaging/apkg/ci/fedora-33:apkg
  <<: *knot-resolver
  script:
    - *setup-project
    - py.test-3 -v ci/tests/test_knot_resolver.py

suse-15-knot-resolver:
  image: $CI_REGISTRY/packaging/apkg/ci/suse-15:apkg
  <<: *knot-resolver
  script:
    - *setup-project
    - py.test3 -v ci/tests/test_knot_resolver.py


# docs published to GitLab Pages: https://packaging.pages.nic.cz/apkg/

pages:
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
    - public
  only:
    - master
  except:
    variables:
      - $INTEGRATION
