variables:
  LC_ALL: C.UTF-8

stages:
  - test
  - test-py35
  - deploy


image: $CI_REGISTRY/packaging/apkg/ci/python-current:apkg


flake8:
  stage: test
  script:
    - tox -e flake8

pylint:
  stage: test
  script:
    - tox -e pylint

unit:
  stage: test
  script:
    - tox -e unit

self:
  stage: test
  script:
    - tox -e self

unit-py35:
  image: $CI_REGISTRY/packaging/apkg/ci/python-3.5:apkg
  stage: test-py35
  script:
    # use py.test directly to test system packages
    - py.test-3 tests/unit

self-py35:
  image: $CI_REGISTRY/packaging/apkg/ci/python-3.5:apkg
  stage: test-py35
  script:
    # use py.test directly to test system packages
    - py.test-3 tests/self


# docs published to GitLab Pages: https://packaging.pages.nic.cz/apkg/
pages:
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
    - public
  only:
    - master
