variables:
  LC_ALL: C.UTF-8

stages:
  - test
  - deploy


image: $CI_REGISTRY/packaging/apkg/ci/python-current:apkg


flake8:
  stage: test
  script:
    - tox -e flake8

pylint:
  stage: test
  script:
    - tox -e pylint

unit:
  stage: test
  script:
    - tox -e unit

integration:
  stage: test
  script:
    - tox -e integration

self:
  stage: test
  script:
    # `python3 -m build` causes issues in tox in docker container
    # use py.test directly
    - pip3 install -r requirements.txt
    - python3 setup.py develop --user
    - py.test-3 tests/self


# docs published to GitLab Pages: https://packaging.pages.nic.cz/apkg/
pages:
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
    - public
  only:
    - master
