# Read the Docs configuration file for apkg (MkDocs)
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
build:
  os: debian-12
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: doc-requirements.txt
