site_name: apkg
site_url: https://pkg.labs.nic.cz/pages/apkg/
repo_url: https://gitlab.nic.cz/packaging/apkg
edit_uri: ""
nav:
  - index.md
  - intro.md
  - news.md
  - install.md
  - guide.md
  - commands.md
  - config.md
  - pkgstyles.md
  - templates.md
  - errors.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: True

plugins:
  - macros:
      module_name: docs

theme:
  name: material
  logo: img/apkg.png
