site_name: apkg
site_url: https://pkg.labs.nic.cz/pages/apkg/
repo_url: https://gitlab.nic.cz/packaging/apkg
edit_uri: ""
nav:
  - index.md
  - intro.md
  - news.md
  - platforms.md
  - install.md
  - guide.md
  - users.md
  - commands.md
  - config.md
  - cache.md
  - compat.md
  - distro.md
  - pkgstyles.md
  - templates.md
  - templatevars.md
  - test.md
  - errors.md

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True

plugins:
  - macros:
      module_name: docs

theme:
  name: material
  logo: img/apkg.png
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
