[project]
# optional - is guessed from project dir name by default
name = "apkg"
# needed for make-archive
make_archive_script = "scripts/make-dev-archive.sh"

[upstream]
# needed for get-archive
archive_url = "https://gitlab.nic.cz/packaging/apkg/-/archive/v{{ version }}/apkg-v{{ version }}.tar.gz"
# script to check latest upstream version
version_script = "scripts/upstream-version.py"
