[project]
# recommended - guessed from project dir name by default
name = "apkg"
# recommended - script to create project archive, needed for make-archive
make_archive_script = "scripts/make-archive.sh"

[upstream]
# optional - needed for get-archive
archive_url = "https://gitlab.nic.cz/packaging/apkg/-/archive/v{{ version }}/apkg-v{{ version }}.tar.gz"
# optional - script to check latest upstream version
version_script = "scripts/upstream-version.py"

# optional - custom template variables deb_series and deb_codename
[[template.variables]]
# TODO: rename to deb_series after 0.6 release
python_module = "apkg.templatevars.debseries"

[apkg]
# recommended - apkg compat level
compat = 6
