[project]
# recommended - guessed from project dir name by default
name = "apkg"
# recommended - script to create project archive, needed for make-archive
make_archive_script = "scripts/make-dev-archive.sh"

[upstream]
# optional - needed for get-archive
archive_url = "https://gitlab.nic.cz/packaging/apkg/-/archive/v{{ version }}/apkg-v{{ version }}.tar.gz"
# optional - script to check latest upstream version
version_script = "scripts/upstream-version.py"

[apkg]
# recommended - apkg compat level
compat = 1
