[project]
name = "apkg-example-templates"
make_archive_script = "distro/scripts/make-archive.sh"

[apkg]
compat = 5

[[distro.aliases]]
name = "deb-zzz"
distro = ["debian < 10", "ubuntu <= 18.04"]

[[distro.aliases]]
name = "deb-old"
distro = ["debian < 12", "ubuntu < 22.04"]

[[distro.aliases]]
name = "el-8"
distro = ["rocky == 8", "centos == 8", "rhel == 8"]

[template]
ignore_files = ['.*', 'IGNORED']
plain_copy_files = ['*.patch', 'COPY?ONLY']
